[workspace]
resolver = "2"
members = [ "ipa-compact-step","ipa-core", "ipa-macros"]

[profile.release]
incremental = true
lto = "thin"

[profile.bench]
debug-assertions = true

[profile.bench-dhat]
inherits = "bench"
debug-assertions = false
incremental = true
lto = "thin"
debug = 1
