extend=[
    { path = "grcov.makefile.toml" }
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--tests", "--", "-D","warnings", "-D", "clippy::pedantic"]

[tasks.coverage]
alias="coverage_grcov"

[tasks.doctest]
command = "cargo"
args = ["test", "--doc"]

[tasks.touch]
dependencies = [
    "check",
    "format",
    "clippy",
    "doctest",
    "test",
]

[tasks.san]
dependencies = [
    "touch",
    "doctest",
    "test",
]
