[package]
name = "raw-ipa-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-elgamal = "0.4"
rand_core = "0.6"

[dev-dependencies]
rand = "0.8"
hex = "0.4"
